### ISSUE TITLE
Bot not working anymore

### ISSUE THREAD

**Issue by ccrowles** [cod119/TeleSaucenao_bot#1]
The bot is not answering since today, I send pictures and it doesn't even start searching. Issue confirmed by other users as well.

**Comment by ghost** [comment]
Sorry for inconvenience. I am checking out now. Please wait for a second.

**Comment by ccrowles** [comment]
Now it works again, thank you so much!

**Comment by ghost** [comment]
Thank you Now the bot is working. Please enjoy our service!

**Comment by ccrowles** [comment]
Sorry to bother, but it's not working again, for two days now...

**Comment by ghost** [comment]
Thank you for your report. I will check it out asap.

**Comment by ghost** [comment]
Sorry for your inconvenience. My server seems to be not stable. I restarted it so it would work for a while. If you have any problem with my bot, please contact through github issue or send me a message to "saucebot1" at telegram. Thx

**Comment by ccrowles** [comment]
Thanks! For now it's working again. :)

**Comment by ccrowles** [comment]
Once again it has stopped working since the 8th of April...

**Comment by ghost** [comment]
Sorry for the inconvenience and thanks for your report. There has been unexpected error on the server and now it is repaired. Thanks again and pls enjoy.
